add table view
QuanNH97/DemoItune pull request #2
Opened 2020-08-31 01:47 UTC by QuanNH97

2020-08-31 02:20 UTC, thanhhvt7196 commented on DemoItune/Models/Cell.swift
> +struct Cell: Hashable {
model tại sao lại đặt tên là Cell.

2020-08-31 02:20 UTC, thanhhvt7196 commented on DemoItune/Models/Cell.swift
> +        if let viewCount = viewCountArray.randomElement() {
viết luôn viewCount = viewCountArray.randomElement() ?? 0 ở khai phần khai báo biến

2020-08-31 02:20 UTC, thanhhvt7196 commented on DemoItune/Models/Topic.swift
> +    var cell: [Cell]
sửa lại cách đặt tên

2020-08-31 02:20 UTC, thanhhvt7196 commented on DemoItune/Ultilties/Helper/DataHelper.swift
> +    let cellArray6 = [Cell(id: 50, name: "Ed Sheeran", image: "ed_sheeran.png"), Cell(id: 51, name: "Rita Ora", image: "rita_ora.png"), Cell(id: 52, name: "Eminem", image: "eminem.png"), Cell(id: 53,
sửa cách đặt tên
Array nếu dài thì nên xuống dòng để tiện theo dõi thay vì viết tren cùng 1 dòng, dài và khó nhìn. 
private các biến nếu có thể

2020-08-31 02:20 UTC, thanhhvt7196 commented on DemoItune/Ultilties/Helper/DataHelper.swift
> +        let topicArray: [Topic] = [Topic(id: 0, title: "Hots now", type: .album, cell: createHotAlbumList()) ,Topic(id: 1, title: "Sơn Tùng", type: .album, cell: cellArray1), Topic(id: 2, title: "Moo
Array nếu dài thì nên xuống dòng để tiện theo dõi thay vì viết tren cùng 1 dòng, dài và khó nhìn.

2020-08-31 02:20 UTC, thanhhvt7196 commented on DemoItune/Ultilties/Helper/Formatter.swift
> +    func formatNumber(number: Int64) -> String {
có thể dùng singleton

2020-08-31 02:20 UTC, thanhhvt7196 commented on DemoItune/ViewControllers/HomeViewController.swift
> +class HomeViewController: UIViewController, AlbumTableViewCellDelegate {
adapt delegate ngoài thì nên viết thành 1 extension xuống dưới cùng để tiện theo dõi như đã làm với UITableViewDelegate

2020-08-31 02:20 UTC, thanhhvt7196 commented on DemoItune/ViewControllers/HomeViewController.swift
> +    var data = DataHelper().initData()
private các biến nếu có thể

2020-08-31 02:20 UTC, thanhhvt7196 commented on DemoItune/ViewControllers/HomeViewController.swift
> +    override func viewDidLoad() {
chú ý coding convention: cách dòng giữa outlet và code

2020-08-31 02:20 UTC, thanhhvt7196 commented on DemoItune/Views/Album/AlbumCollectionViewCell.swift
> +    }
cách dòng

2020-08-31 02:20 UTC, thanhhvt7196 commented on DemoItune/ViewControllers/HomeViewController.swift
> +    func offsetDidChange(indexPath: IndexPath, contentOffset: CGPoint) {
hàm này không phải của delegate này, nên đặt đúng chỗ

2020-08-31 02:20 UTC, thanhhvt7196 commented on DemoItune/Views/Album/AlbumTableViewCell.swift
> +    var delegate: AlbumTableViewCellDelegate?
để tham chiếu yếu để tránh memory leak

2020-08-31 02:20 UTC, thanhhvt7196 commented on DemoItune/Views/Album/AlbumTableViewCell.swift
> +    var albumCellArray: [Cell] = []
private

2020-08-31 02:20 UTC, thanhhvt7196 commented on DemoItune/Views/Album/AlbumTableViewCell.swift
> +        selectionStyle = .none
đặt ở awakefromnib

2020-08-31 02:20 UTC, thanhhvt7196 commented on DemoItune/Views/Album/AlbumTableViewCell.swift
> +        albumCollectionView.reloadData()
xem lại logic xem reload ở đây có đúng ko

2020-08-31 02:20 UTC, thanhhvt7196 commented on DemoItune/Views/Album/AlbumTableViewCell.swift
> +        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "AlbumCollectionViewCell", for: indexPath) as! AlbumCollectionViewCell
không force unwrap

2020-08-31 02:20 UTC, thanhhvt7196 commented on DemoItune/ViewControllers/HomeViewController.swift
> +            let cell = tableView.dequeueReusableCell(withIdentifier: "ArtistTableViewCell", for: indexPath) as! ArtistTableViewCell
không force unwrap

2020-08-31 02:20 UTC, thanhhvt7196 commented on DemoItune/ViewControllers/HomeViewController.swift
> +            let cell = tableView.dequeueReusableCell(withIdentifier: "AlbumTableViewCell", for: indexPath) as! AlbumTableViewCell
không force unwrap

2020-08-31 02:20 UTC, thanhhvt7196 commented on DemoItune/Views/Artist/ArtistCollectionViewCell.swift
> +    override func awakeFromNib() {
cách dòng

2020-08-31 02:20 UTC, thanhhvt7196 commented on DemoItune/Views/Artist/ArtistCollectionViewCell.swift
> +
thừa khoảng cách

2020-08-31 02:20 UTC, thanhhvt7196 commented on DemoItune/Views/Artist/ArtistCollectionViewCell.swift
> +
thừa khoảng cách

2020-08-31 02:20 UTC, thanhhvt7196 commented on DemoItune/Views/Artist/ArtistTableViewCell.swift
> +
thừa khoảng cách

2020-08-31 02:20 UTC, thanhhvt7196 commented on DemoItune/Views/Artist/ArtistTableViewCell.swift
> +    var delegate: AlbumTableViewCellDelegate?
để tham chiếu yếu để tránh memory leak

2020-08-31 02:20 UTC, thanhhvt7196 commented on DemoItune/Views/Artist/ArtistTableViewCell.swift
> +    var artistCellArray: [Cell] = []
private

2020-08-31 02:20 UTC, thanhhvt7196 commented on DemoItune/Views/Artist/ArtistTableViewCell.swift
> +        artistCollectionView.reloadData()
tương tự như trên, kiểm tra lại logic ở phần này

2020-08-31 02:20 UTC, thanhhvt7196 commented on DemoItune/Views/Artist/ArtistTableViewCell.swift
> +        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "ArtistCollectionViewCell", for: indexPath) as! ArtistCollectionViewCell
không force unwrap

2020-08-31 02:24 UTC, mlh-hieutq requested changes

2020-08-31 02:24 UTC, mlh-hieutq commented on DemoItune/Models/Cell.swift
> +struct Cell: Hashable {
Anh nghĩ cái Cell này nên được đổi tên để cho rõ nghĩa hơn.

2020-08-31 02:24 UTC, mlh-hieutq commented on DemoItune/ViewControllers/HomeViewController.swift
> +            let cell = tableView.dequeueReusableCell(withIdentifier: "AlbumTableViewCell", for: indexPath) as! AlbumTableViewCell
Không nên **force cast** em nhé.

2020-08-31 02:24 UTC, mlh-hieutq commented on DemoItune/ViewControllers/HomeViewController.swift
> +            let cell = tableView.dequeueReusableCell(withIdentifier: "ArtistTableViewCell", for: indexPath) as! ArtistTableViewCell
Không nên **force cast** em nhé.

2020-08-31 02:24 UTC, mlh-hieutq commented on DemoItune/Views/Album/AlbumCollectionViewCell.swift
> +    @IBOutlet weak var albumImageImage: UIImageView!
Sửa **albumImageImage** thành **albumImageView**

2020-08-31 02:24 UTC, mlh-hieutq commented on DemoItune/ViewControllers/HomeViewController.swift
> +extension HomeViewController: UITableViewDelegate {
Em check lại xem **UITableViewDelegate** có chứa **offsetDidChange** không nhé.

2020-08-31 04:48 UTC, thanhhvt7196 commented on DemoItune/Models/Card.swift
> +let viewCountArray: [Int64] = [100000, 123045, 150876, 213532, 345678, 432123, 569690, 780907, 900789, 1130234, 5567405, 9678879]
đặt trong 1 struct Constant hay gì đó tương tự nhé, đừng để biến global thế này

2020-08-31 04:48 UTC, thanhhvt7196 commented on DemoItune/Models/Card.swift
> +struct Card: Hashable {
nên chia riêng ra 2 model khác nhau, 1 là album và 1 là artist, không nên dùng chung

2020-08-31 04:48 UTC, thanhhvt7196 commented on DemoItune/Ultilties/Helper/DataHelper.swift
> +
thừa dấu cách

2020-08-31 04:48 UTC, thanhhvt7196 commented on DemoItune/Views/Artist/ArtistTableViewCell.swift
> +    var indexPath: IndexPath = IndexPath()
private

2020-08-31 04:48 UTC, thanhhvt7196 commented on DemoItune/Views/Artist/ArtistTableViewCell.swift
> +
thừa dấu cách

2020-08-31 04:48 UTC, thanhhvt7196 commented on DemoItune/Views/Album/AlbumTableViewCell.swift
> +
thừa dấu cách

2020-08-31 04:48 UTC, thanhhvt7196 commented on DemoItune/Views/Album/AlbumCollectionViewCell.swift
> +    var formatter = Formatter()
khai báo ở trong configCell

2020-08-31 04:48 UTC, thanhhvt7196 commented on DemoItune/Views/Album/AlbumTableViewCell.swift
> +    var indexPath: IndexPath = IndexPath()
private

2020-09-01 02:49 UTC, mlh-hieutq requested changes

2020-09-01 02:49 UTC, mlh-hieutq commented on DemoItune/ViewControllers/MainTabbarController.swift
> +        displayMusicView.bottomAnchor.constraint(equalTo: view.bottomAnchor, constant: -49).isActive = true
Ý nghĩa của con số 49 này là gì em?

2020-09-01 02:49 UTC, mlh-hieutq commented on DemoItune/Views/Artist/ArtistCollectionViewCell.swift
> +    func configCell(cell: Artist) {
Em sửa **func configCell(cell: Artist)** thành **func configCell(artist: Artist)**

2020-09-01 02:49 UTC, mlh-hieutq commented on DemoItune/Views/PlayMusic/PlayMusicView.swift
> +    override init(frame: CGRect) {
Em xóa hết comment code này đi nhé

2020-09-01 02:49 UTC, mlh-hieutq commented on DemoItune/Views/Album/AlbumCollectionViewCell.swift
> +        albumImageView.image = UIImage(named: cell.image)
Em sửa **func configCell(cell: Album)** thành **func configCell(album: Album)**

2020-09-01 02:51 UTC, QuanNH97 commented on DemoItune/ViewControllers/MainTabbarController.swift
> +        displayMusicView.bottomAnchor.constraint(equalTo: view.bottomAnchor, constant: -49).isActive = true
chiều cao tabbar ấy anh

2020-09-01 02:53 UTC, mlh-hieutq commented on DemoItune/ViewControllers/MainTabbarController.swift
> +        displayMusicView.bottomAnchor.constraint(equalTo: view.bottomAnchor, constant: -49).isActive = true
Có trường hợp nào chiều cao tabBar không bằng 49 không em?

2020-09-01 02:58 UTC, mlh-hieutq approved these changes

2020-09-01 03:00 UTC, thanhhvt7196 approved these changes

2020-09-01 03:00 UTC, merged